// Generated by CoffeeScript 1.6.3
(function() {
  describe("Raffler Views", function() {
    return it("should exist", function() {
      return expect(Raffler.Views).toBeDefined();
    });
  });

}).call(this);
