// Generated by CoffeeScript 1.6.3
(function() {
  describe("Raffler Views", function() {
    it("should exist", function() {
      return expect(Raffler.Views).toBeDefined();
    });
    it("should have 'createEntry'", function() {
      return expect(Raffler.Views.Events);
    });
    it("should have 'drawWinner'", function() {
      return expect(Raffler.Views.Events);
    });
    it("should have 'clearWinner'", function() {
      return expect(Raffler.Views.Events);
    });
    return it("should have 'kill'", function() {
      return expect(Raffler.Views.Events);
    });
  });

}).call(this);
