// Generated by CoffeeScript 1.6.3
(function() {
  describe("Raffler App namespace", function() {
    return it("should be defined", function() {
      return expect(Raffler).toBeDefined();
    });
  });

}).call(this);
